updateBS <- c("Barguna", "Barisal", "Bhola", "Jhalokati",
              "Patuakhali",
              "Pirojpur",
              "Bandarban",
              "Brahamanbaria",
              "Chandpur",
              "Chittagong",
              "Comilla",
              "Cox's Bazar",
              "Feni",
              "Khagrachhari",
              "Lakshmipur",
              "Noakhali",
              "Rangamati",
              "Dhaka",
              "Faridpur",
              "Gazipur",
              "Gopalganj",
              "Jamalpur",
              "Kishoreganj",
              "Madaripur",
              "Manikganj",
              "Munshiganj",
              "Mymensingh",
              "Narayanganj",
              "Narsingdi",
              "Netrakona",
              "Rajbari",
              "Shariatpur",
              "Sherpur",
              "Tangail",
              "Bagerhat",
              "Chuadanga",
              "Jessore",
              "Jhenaidah",
              "Khulna",
              "Kushtia",
              "Magura",
              "Meherpur",
              "Narail",
              "Satkhira",
              "Habiganj",
              "Maulvibazar",
              "Sunamganj",
              "Sylhet",
              "Bogra",
              "Joypurhat",
              "Naogaon",
              "Natore",
              "Nawabganj",
              "Pabna",
              "Rajshahi",
              "Sirajganj",
              "Dinajpur",
              "Gaibandha",
              "Kurigram",
              "Lalmonirhat",
              "Nilphamari",
              "Panchagarh",
              "Rangpur",
              "Thakurgaon",
              "Bagmati",
              "Janakpur",
              "Narayani",
              "Koshi",
              "Mechi",
              "Sagarmatha",
              "Mahakali",
              "Seti",
              "Karnali",
              "Rapti",
              "Bheri",
              "Dhawalagiri",
              "Gandaki",
              "Lumbini",
              "Andaman Islands",
              "Nicobar Islands",
              "Adilabad",
              "Anantapur",
              "Chittoor",
              "Cuddapah",
              "East Godavari",
              "Guntur",
              "Hyderabad",
              "Karimnagar",
              "Khammam",
              "Krishna",
              "Kurnool",
              "Mahbubnagar",
              "Medak",
              "Nalgonda",
              "Nellore",
              "Nizamabad",
              "Prakasam",
              "Rangareddi",
              "Srikakulam",
              "Vishakhapatnam",
              "Vizianagaram",
              "Warangal",
              "West Godavari",
              "Barpeta",
              "Cachar",
              "Darrang",
              "Dhuburi",
              "Dibrugarh",
              "Goalpara",
              "Golaghat",
              "Kamrup",
              "Karbi Anglong",
              "Karimganj",
              "Nagaon",
              "Nalbari",
              "North Cachar Hills",
              "Sibsagar",
              "Sonitpur",
              "Bongaigaon",
              "Dhemaji",
              "Hailakandi",
              "Jorhat",
              "Kokrajhar",
              "Lakhimpur",
              "Marigaon",
              "Tinsukia",
              "Delhi",
              "North Goa",
              "South Goa",
              "Ahmadabad",
              "Amreli",
              "Banas Kantha",
              "Bharuch",
              "Bhavnagar",
              "Gandhinagar",
              "Jamnagar",
              "Junagadh",
              "Kachchh",
              "Kheda",
              "Mahesana",
              "Rajkot",
              "Sabar Kantha",
              "Surat",
              "Surendranagar",
              "The Dangs",
              "Vadodara",
              "Valsad",
              "Anand",
              "Dahod",
              "Narmada",
              "Navsari",
              "Panch Mahals",
              "Patan",
              "Porbandar",
              "Ambala",
              "Bhiwani",
              "Gurgaon",
              "Hisar",
              "Jind",
              "Karnal",
              "Kurukshetra",
              "Mahendragarh",
              "Rohtak",
              "Sirsa",
              "Sonepat",
              "Faridabad",
              "Fatehabad",
              "Jhajjar",
              "Kaithal",
              "Panchkula",
              "Panipat",
              "Rewari",
              "Yamuna Nagar",
              "Bilaspur",
              "Chamba",
              "Hamirpur",
              "Kangra",
              "Kinnaur",
              "Kullu",
              "Lahul and Spiti",
              "Mandi",
              "Shimla",
              "Sirmaur",
              "Solan",
              "Una",
              "Belgaum",
              "Bellary",
              "Bidar",
              "Bijapur",
              "Chikmagalur",
              "Dakshin Kannad",
              "Dharwad",
              "Gulbarga",
              "Hassan",
              "Kodagu",
              "Kolar",
              "Mandya",
              "Mysore",
              "Raichur",
              "Shimoga",
              "Tumkur",
              "Uttar Kannand",
              "Bagalkot",
              "Bangalore Rural",
              "Bangalore Urban",
              "Chamrajnagar",
              "Chitradurga",
              "Davanagere",
              "Gadag",
              "Haveri",
              "Koppal",
              "Udupi",
              "Kannur",
              "Ernakulam",
              "Idukki",
              "Kasaragod",
              "Kottayam",
              "Kozhikode",
              "Malappuram",
              "Palakkad",
              "Pattanamtitta",
              "Kollam",
              "Thrissur",
              "Thiruvananthapuram",
              "Wayanad",
              "Alappuzha",
              "Kavaratti",
              "Akola",
              "Amravati",
              "Bhandara",
              "Buldana",
              "Chandrapur",
              "Dhule",
              "Garhchiroli",
              "Jalgaon",
              "Kolhapur",
              "Latur",
              "Nagpur",
              "Nanded",
              "Nashik",
              "Osmanabad",
              "Pune",
              "Raigarh",
              "Ratnagiri",
              "Sindhudurg",
              "Sangli",
              "Satara",
              "Solapur",
              "Thane",
              "Wardha",
              "Yavatmal",
              "Aurangabad",
              "Ahmednagar",
              "Bid",
              "Gondiya",
              "Hingoli",
              "Jalna",
              "Mumbai Suburban",
              "Mumbai city",
              "Nandurbar",
              "Parbhani",
              "Washim",
              "Bishnupur",
              "Chandel",
              "Churachandpur",
              "East Imphal",
              "Senapati",
              "Tamenglong",
              "Thoubal",
              "Ukhrul",
              "West Imphal",
              "East Garo Hills",
              "East Khasi Hills",
              "Jaintia Hills",
              "West Garo Hills",
              "West Khasi Hills",
              "Ri-Bhoi",
              "South Garo Hills",
              "Aizawl",
              "Lunglei",
              "Champhai",
              "Kolasib",
              "Lawngtlai",
              "Mamit",
              "Saiha",
              "Serchhip",
              "Kohima",
              "Mokokchung",
              "Mon",
              "Phek",
              "Tuensang",
              "Wokha",
              "Zunheboto",
              "Dimapur",
              "Cuttack",
              "Dhenkanal",
              "Ganjam",
              "Kalahandi",
              "Keonjhar",
              "Koraput",
              "Mayurbhanj",
              "Puri",
              "Sambalpur",
              "Sundargarh",
              "Angul",
              "Baleshwar",
              "Baragarh",
              "Bhadrak",
              "Bolangir",
              "Boudh",
              "Deogarh",
              "Gajapati",
              "Jagatsinghpur",
              "Jajpur",
              "Jharsuguda",
              "Kandhamal",
              "Kendrapara",
              "Khordha",
              "Malkangiri",
              "Nabarangpur",
              "Nayagarh",
              "Nuapada",
              "Rayagada",
              "Sonepur",
              "Amritsar",
              "Bathinda",
              "Firozpur",
              "Gurdaspur",
              "Hoshiarpur",
              "Jalandhar",
              "Kapurthala",
              "Ludhiana",
              "Patiala",
              "Rupnagar",
              "Sangrur",
              "Faridkot",
              "Fatehgarh Sahib",
              "Mansa",
              "Moga",
              "Muktsar",
              "Nawan Shehar",
              "Ajmer",
              "Alwar",
              "Banswara",
              "Barmer",
              "Bharatpur",
              "Bhilwara",
              "Bikaner",
              "Bundi",
              "Chittaurgarh",
              "Churu",
              "Dhaulpur",
              "Dungarpur",
              "Ganganagar",
              "Jaipur",
              "Jaisalmer",
              "Jalor",
              "Jhalawar",
              "Jhunjhunun",
              "Jodhpur",
              "Kota",
              "Nagaur",
              "Pali",
              "Sawai Madhopur",
              "Sikar",
              "Sirohi",
              "Tonk",
              "Udaipur",
              "Baran",
              "Dausa",
              "Hanumangarh",
              "Karauli",
              "Rajsamand",
              "East",
              "North Sikkim",
              "South Sikkim",
              "West Sikkim",
              "Thoothukudi",
              "Coimbatore",
              "Dharmapuri",
              "Virudhunagar",
              "Kanniyakumari",
              "Nilgiris",
              "Erode",
              "Pudukkottai",
              "Dindigul",
              "Ramanathapuram",
              "Salem",
              "Thanjavur",
              "Sivaganga",
              "Tiruchchirappalli",
              "Tirunelveli Kattabo",
              "Ariyalur",
              "Chennai",
              "Cuddalore",
              "Kancheepuram",
              "Karur",
              "Madurai",
              "Nagapattinam",
              "Namakkal",
              "Perambalur",
              "Theni",
              "Thiruvallur",
              "Tiruvannamalai",
              "Vellore",
              "Villupuram",
              "North Tripura",
              "South Tripura",
              "West Tripura",
              "Dhalai",
              "Bankura",
              "Barddhaman",
              "Birbhum",
              "Darjiling",
              "Haora",
              "Hugli",
              "Jalpaiguri",
              "Kochbihar",
              "Maldah",
              "Murshidabad",
              "Nadia",
              "Puruliya",
              "Dakshin Dinajpur",
              "East Midnapore",
              "Kolkata",
              "North 24 Parganas",
              "South 24 Parganas",
              "Uttar Dinajpur",
              "West Midnapore",
              "East Siang",
              "Lohit",
              "Lower Subansiri",
              "Tirap",
              "West Siang",
              "Changlang",
              "Lower Dibang Valley",
              "Papum Pare",
              "Aurangabad",
              "Begusarai",
              "Bhagalpur",
              "Darbhanga",
              "Gaya",
              "Gopalganj",
              "Jehanabad",
              "Katihar",
              "Khagaria",
              "Madhubani",
              "Madhepura",
              "Muzaffarpur",
              "Munger",
              "Nalanda",
              "Nawada",
              "Pashchim Champaran",
              "Patna",
              "Purba Champaran",
              "Purnia",
              "Rohtas",
              "Saharsa",
              "Samastipur",
              "Saran",
              "Sitamarhi",
              "Siwan",
              "Vaishali",
              "Araria",
              "Banka",
              "Bhabua",
              "Bhojpur",
              "Buxar",
              "Jamui",
              "Kishanganj",
              "Lakhisarai",
              "Sheikhpura",
              "Sheohar",
              "Supaul",
              "Chandigarh",
              "Durg",
              "Bastar",
              "Bilaspur",
              "Dantewada",
              "Dhamtari",
              "Janjgir-Champa",
              "Jashpur",
              "Kanker",
              "Kawardha",
              "Korba",
              "Koriya",
              "Mahasamund",
              "Raipur",
              "Raj Nandgaon",
              "Surguja",
              "Raigarh",
              "Dadra and Nagar Haveli",
              "Daman",
              "Junagadh",
              "Deoghar",
              "Godda",
              "Lohardaga",
              "Ranchi",
              "Bokaro",
              "Chatra",
              "Dhanbad",
              "Dumka",
              "Garhwa",
              "Giridih",
              "Gumla",
              "Hazaribag",
              "Jamtara",
              "Koderma",
              "Latehar",
              "Pakur",
              "Palamu",
              "Pashchim Singhbhum",
              "Purba Singhbhum",
              "Sahibganj",
              "Saraikela Kharsawan",
              "Simdega",
              "Balaghat",
              "Betul",
              "Bhind",
              "Bhopal",
              "Chhatarpur",
              "Chhindwara",
              "Damoh",
              "Datia",
              "Dewas",
              "Dhar",
              "East Nimar",
              "Guna",
              "Gwalior",
              "Hoshangabad",
              "Indore",
              "Jabalpur",
              "Jhabua",
              "Mandla",
              "Mandsaur",
              "Morena",
              "Narsinghpur",
              "Panna",
              "Raisen",
              "Rajgarh",
              "Ratlam",
              "Rewa",
              "Sagar",
              "Satna",
              "Sehore",
              "Seoni",
              "Shahdol",
              "Shajapur",
              "Shivpuri",
              "Sidhi",
              "Tikamgarh",
              "Ujjain",
              "Vidisha",
              "West Nimar",
              "Anuppur",
              "Ashoknagar",
              "Barwani",
              "Burhanpur",
              "Dindori",
              "Harda",
              "Katni",
              "Neemuch",
              "Sheopur",
              "Umaria",
              "Karaikal",
              "Mahe",
              "Puducherry",
              "Yanam",
              "Agra",
              "Aligarh",
              "Allahabad",
              "Azamgarh",
              "Bahraich",
              "Ballia",
              "Banda",
              "Bara Banki",
              "Bareilly",
              "Basti",
              "Bijnor",
              "Bulandshahr",
              "Deoria",
              "Etah",
              "Etawah",
              "Faizabad",
              "Farrukhabad",
              "Fatehpur",
              "Ghaziabad",
              "Ghazipur",
              "Gonda",
              "Gorakhpur",
              "Hamirpur",
              "Hardoi",
              "Jalaun",
              "Jaunpur",
              "Jhansi",
              "Kanpur",
              "Lakhimpur Kheri",
              "Lalitpur",
              "Lucknow",
              "Mainpuri",
              "Mathura",
              "Meerut",
              "Mirzapur",
              "Moradabad",
              "Muzaffarnagar",
              "Pilibhit",
              "Pratapgarh",
              "Rae Bareli",
              "Rampur",
              "Saharanpur",
              "Shahjahanpur",
              "Sitapur",
              "Sultanpur",
              "Unnao",
              "Varanasi",
              "Ambedkar Nagar",
              "Auraiya",
              "Badaun",
              "Baghpat",
              "Balrampur",
              "Chandauli",
              "Chitrakoot",
              "Firozabad",
              "Gautam Buddha Nagar",
              "Hathras",
              "Jyotiba Phule Nagar",
              "Kannauj",
              "Kanpur Dehat",
              "Kaushambi",
              "Kushinagar",
              "Maharajganj",
              "Mahoba",
              "Mau",
              "Sant Kabir Nagar",
              "Sant Ravi Das Nagar",
              "Shravasti",
              "Siddharth Nagar",
              "Sonbhadra",
              "Dehra Dun",
              "Pauri Garhwal",
              "Pithoragarh",
              "Almora",
              "Bageshwar",
              "Chamoli",
              "Champawat",
              "Haridwar",
              "Naini Tal",
              "Rudra Prayag",
              "Tehri Garhwal",
              "Udham Singh Nagar",
              "Uttarkashi")
